## -*- python -*-


Import('env')
##
# WarpM library files
##

# source files in lib
sources = [
        'wxfunction_register.cc',
        'wxpdggeometry.cc',
	'wxobject.cc',
	'wxcrypt.cc',
	'wxcryptset.cc',
        #'wxcreator.cc',
	'wxcryptsetlexer.cc',
	'wxexcept.cc',
        'wxexprfunction.cc',
        'wxexprparser.cc',
	'wxlogger.cc',
	'wxlogstream.cc',
	'wxlogstreamstrm.cc',
	'wxmpimsg.cc',
	'wxmpimsgop.cc',
	'wxmpimsgtmpl.cc',
        'mup/muParser.cpp',
        'mup/muParserBytecode.cpp',
        'mup/muParserInt.cpp',
        'mup/muParserTokenReader.cpp',
        'mup/muParserBase.cpp',
        'mup/muParserCallback.cpp',
        'mup/muParserError.cpp',
           ]

##
# compile sources and add them to list of objects built
##
objs = []
for s in sources:
    o = env.Object(s)
    objs.append(o)

Return('objs')
