#ifndef __wxrecordhandler__h__
#define __wxrecordhandler__h__

// WarpX includes
#include "wxobject.h"
#include "wxcreator.h"
#include "wxcryptset.h"

// std includes
#include <iostream>
#include <string>
#include <fstream>
#include <ios>

/**
 * Class to handle log messsages generated by WarpX logging system. In
 * general this class should not be used directly but one of its
 * children used instead.
 */
class WxLogRecordHandler : public WxObject
{
  public:
/**
 * Create new handler and attach std::cout to it.
 */
    WxLogRecordHandler() 
      : _outStream(0), _owns(false) {
      _outStream = &std::cout;
    }

    virtual ~WxLogRecordHandler() {
      // delete stream if owning it
      if (_owns) delete _outStream;
    }

/**
 * Set the output stream to one specified. Note that by default the
 * caller of this method owns the stream and is hence responsible for
 * closing it.
 */
    void setStream(std::ostream *stream) {
      _outStream = stream;
    }

/**
 * Write message 'msg' to the output stream.
 */
    void write(const std::string& msg) {
      *_outStream << msg;
      *_outStream << std::flush;
    }

/**
 * Set if the stream to which data is being written is owned by the
 * handler.
 *
 * @param handlerOwns True if handler owns the stream and false if
 * caller owns the stream.
 */
    void setOwns(bool handlerOwns) {
      _owns = handlerOwns;
    }

/**
 * Returns true if handler owns the stream and false otherwise
 */
    bool owns() const {
      return _owns;
    }

  private:
    std::ostream *_outStream;
    bool _owns;
};

/**
 * Class to log messages to an open stream.
 */
class WxStreamHandler : public WxLogRecordHandler
{
  public:

    WxStreamHandler()
      : WxLogRecordHandler() {
    }

/**
 * Create new handler with the specified output stream
 */
    WxStreamHandler(std::ostream *stream) {
      setStream(stream);
    }

};
// register this handler
static WxCreator<WxStreamHandler, WxLogRecordHandler> __sh("streamHandler");

/**
 * Class to log messages to a file. By default the file is truncated
 * while opening it.
 */
class WxFileHandler : public WxLogRecordHandler
{
  public:

    WxFileHandler() 
      : WxLogRecordHandler(), _file(0) {
    }

/**
 * Create new handler to write log messages to specified file. By
 * default the file is truncated on opening. However, the open mode
 * can be specified, for example, to append to an existing file.
 */
    WxFileHandler(const std::string& fname, std::ios_base::openmode mode=std::ios_base::trunc) {
      // open a file with specified mode and set it as the output stream
      _file = new std::ofstream(fname.c_str(), mode);
      setStream(_file);
    }

    ~WxFileHandler() {
      delete _file;
    }

/**
 * Setup handler from supplied cryptset
 */
    void setup(const WxCryptSet& wxc) {
      // read file and open it for logging
      std::string fname = wxc.get<std::string>("file");
      if (_file)
        // need to close _file if it is already open
        delete _file;
      _file = new std::ofstream(fname.c_str());
      setStream(_file);
    }

  private:
    std::ofstream *_file;
};
// register this handler
static WxCreator<WxFileHandler, WxLogRecordHandler> __fh("fileHandler");

#endif // __wxrecordhandler__h__
