## -*- python -*-


Import('env')
##
# Apollo library files
##

# source files in lib
sources = [
	'apsubsolver.cc',
	'apsubsolverstep.cc',
        'apdomaindecompcheck.cc',
        'apsubsolver_register.cc',
        'apfvm2dscheme.cc',
           ]

##
# compile sources and add them to list of objects built
##
objs = []
for s in sources:
    o = env.Object(s)
    objs.append(o)

Return('objs')
