## -*- python -*-

##
# Build multifluid equation systems
##

Import('env')

# name of library built with code in this file


# source files in lib
sources = [
           'wxtwofluidrmfbc.cc',
           'wxtwofluidconductingwallbc.cc',
           'aptwofluiddielectricbc.cc',
           'aptwofluidrmfantennabc.cc',
           'aptwofluidrmfwithharmonics.cc',
           'aptwofluidsimplifiedrmfbc.cc',
           'aptualiabadilimiter.cc',
           'aptwofluidomfbc.cc',
           'AtomX.cpp',
           'CR_BKE.cpp',
           'CRParams.cpp',
           'KRates.cpp',
           'KRatesGrp.cpp',
           'MathX.cpp',
           'myIO.cpp',
           'hcubature.c',
           'apthreefluidconstantbc.cc'
            ]

##
# compile sources and add them to list of objects built
##
objs = []
for s in sources:
    o = env.Object(s)
    objs.append(o)

Return('objs')
