## -*- python -*-

##
# Build advection equation systems
##

Import('env')

# name of library built with code in this file


# source files in lib
sources = [
	'wxeulereqn.cc',
        'wxisentropicvortexbc.cc',
        'wxeulerdirichletbc.cc',
        'wxhesthavenwarburtoneulerlimiter.cc',
        'wxeulerinflowbc.cc',
        'wxeulerwallbc.cc',
        'wxeulerzerogradientbc.cc',
        'apeulerentropyeqn.cc',
        'apeulerinflow_entropybc.cc',
           ]

##
# compile sources and add them to list of objects built
##
objs = []
for s in sources:
    o = env.Object(s)
    objs.append(o)

Return('objs')
