#!/usr/bin/env python3
r"""Write a shell fragment defining paths to Apollo's executable and scripts.

Source the result to get:

    APOLLO      the solver executable
    APOLLO_PRE  the input-deck preprocessor
    APOLLO_PLOT the plotting script

    python3 scripts/wxpaths.py > apollo-paths.sh && . apollo-paths.sh

The old names (SERWARPX, PARWARPX, PREWARPX, PLOTWARPX) are kept as aliases for
anything that still refers to them, but they pointed at src/build/xwarpx/xwarpx
and src/build-par/xwarpx/xwarpx - paths from the WarpM project Apollo descends
from, which this build has never produced. They now point at the real binaries.

This used to run its body at import time and write wxpaths.sh into whatever the
current directory happened to be, so merely importing the module littered the
working tree. It writes to stdout under a __main__ guard instead.
"""

import os
import sys


def paths(top=None):
    """Return the shell fragment as a string."""
    if top is None:
        top = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    opt = os.path.join(top, 'src', 'build-opt', 'apollo')
    debug = os.path.join(top, 'src', 'build-debug', 'apollo')
    pre = os.path.join(top, 'scripts', 'wxinpparse.py')
    plot = os.path.join(top, 'scripts', 'wxplot.py')
    return (
        '# Generated by scripts/wxpaths.py - source this file.\n'
        f'APOLLO={opt}\n'
        f'APOLLO_DEBUG={debug}\n'
        f'APOLLO_PRE={pre}\n'
        f'APOLLO_PLOT={plot}\n'
        '# Legacy names, kept for existing scripts.\n'
        f'SERWARPX=$APOLLO\n'
        f'PARWARPX=$APOLLO\n'
        f'PREWARPX=$APOLLO_PRE\n'
        f'PLOTWARPX=$APOLLO_PLOT\n'
        'export APOLLO APOLLO_DEBUG APOLLO_PRE APOLLO_PLOT\n'
        'export SERWARPX PARWARPX PREWARPX PLOTWARPX\n'
    )


if __name__ == '__main__':
    out = paths()
    if len(sys.argv) > 1:
        with open(sys.argv[1], 'w') as fh:
            fh.write(out)
        print(f'wrote {sys.argv[1]}', file=sys.stderr)
    else:
        sys.stdout.write(out)
