## -*- python -*-

Import('env')

##
# Directories searched when a project file uses angle bracket #include<file> syntax
##
incs = [
        '#lib',
        '#lapack_lite',
        '#solvers',
	'#subsolvers',
        '#hyper',
        '#hyperapps',
	'#xapollo',
    ]
env.Append(CPPPATH = incs)

##
# Primary list of sources collected through hierarchical SConscript calls
##
objs = []
objs.append(env.SConscript('xapollo/SConscript', exports='env') )
objs.append(env.SConscript('lib/SConscript', exports='env') )
objs.append(env.SConscript('lapack_lite/SConscript', exports='env') )
objs.append(env.SConscript('solvers/SConscript', exports='env') )
objs.append(env.SConscript('subsolvers/SConscript', exports='env') )
objs.append(env.SConscript('hyper/SConscript', exports='env') )
objs.append(env.SConscript('hyperapps/SConscript', exports='env') )

##
# build Apollo executable for specified target configurations
##
env.Program('apollo', objs)
