## -*- python -*-


Import('env')
##
# Apollo hyper files
##

# source files in lib
sources = [
        'wxhyperboliceqn.cc',
        'wxhyperboliceqnset.cc',
        'wxhyperbolicsrc.cc',
        'wxhyperbolicsrcset.cc',
        'aphyperscheme_register.cc',
           ]

##
# compile sources and add them to list of objects built
##
objs = []
for s in sources:
    o = env.Object(s)
    objs.append(o)

Return('objs')
