## -*- python -*-


Import('env')
##
# Apollo solvers files
##

# source files in lib
sources = [
        'apsolver.cc',
        'wxsolverbase.cc',
        'wxstepper.cc',
        'wxgridbc.cc',
        'wxnodaldglimiter.cc',
        'apnodaldgcalculategradients.cc'
           ]

##
# compile sources and add them to list of objects built
##
objs = []
for s in sources:
    o = env.Object(s)
    objs.append(o)

Return('objs')
